apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: simple-strimzi
  namespace: strimzi
spec:
  entityOperator:
    topicOperator:
      resources: {}
  kafka:
    config:
      log.retention.hours: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    listeners:
      plain: {}
      tls: {}
    replicas: 1
    resources: {}
    storage:
      size: 10Gi
      type: persistent-claim
  zookeeper:
    replicas: 1
    resources: {}
    storage:
      size: 1Gi
      type: persistent-claim
